version: '3.8'

services:
  cv-creator:
    build: .
    container_name: cv-creator-llm
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - TEXT_MODEL=gemma:2b
      - VISION_MODEL=llama3.2-vision:11b
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./samples:/app/samples
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
